### PR TITLE
Fixed Felinids for the new action entities

### PR DESCRIPTION
**Pull request by iNV3RT3D**
works now :)

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
oh fuck what did i do i just merged upstream :skull:

**Comment by VasilisThePikachu** [comment]
ok im taking your changes manually cause I fucked something, it will be merged manually

**Comment by VasilisThePikachu** [comment]
Today in class we learned maintainers can submit commits to peoples pr and git wont tell you that

**Comment by iNV3RT3D** [comment]
Outstanding

**Pull request closed without merging**
